name: Paraphraser CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Run Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Dependencies Installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Code Style Check
        run: |          
          python -m pylint $(git ls-files '*.py')

      - name: Black Check
        run: |
          python -m black --check --config pyproject.toml $(git ls-files '*.py')

      - name: MyPy Check
        run: |
          python -m mypy $(git ls-files '*.py')

      - name: Flake8 Check
        run: |
          python -m flake8 $(git ls-files '*.py')

      - name: Docstrings Check
        run: |
          python -m pydoctest --config pydoctest.json

      - name: Running Tests
        run: |
          python -m pytest tests